name: CI/CD Pipeline for Node.js 23 with Docker

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
  pull_request:
    branches:
      - main  # Runs on PRs targeting main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.0.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node23-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/node23-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/node23-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node23-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/node23-app:latest

  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Authenticate with Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
